Adding JSON validation on precommit and during code generation
The version of the SetupForDevelopment.sh has been increase forcing
and update to the .git/hooks repository along with updates to the
configuration variables.

Adding verbose JSON validation before code generation, conditional on
having Python. The Lua parser is not strict nor does it give
reasonable error messages for parsing errors. The Python's json module
provides validation along with verbose error messages including the
line and column number.

Adding basic precommit hook to check that the json are valid with
minimal Python. This hook should be required to commit json changes,
but it's expected the developer will use the building JSON validation
to get verbose error messages.

Change-Id: I933b587579627fa2619356d3979221a0de3548d3

diff --git a/Utilities/Hooks/pre-commit b/Utilities/Hooks/pre-commit
--- a/Utilities/Hooks/pre-commit
+++ b/Utilities/Hooks/pre-commit
@@ -69,3 +69,33 @@ test -z "$bad" || die "$bad"
 #-----------------------------------------------------------------------------
 # Style hooks.
 . "${BASH_SOURCE%/*}/pre-commit-style.bash"
+
+# Validate json files
+validate_json() {
+    changes=$(git diff-files -- "$1") &&
+    if test -n "$changes"; then
+        die "Cannot validate '$1' with work tree changes."
+    fi &&
+    out=$($python_exe -c "import sys, json; json.load( file( sys.argv[1], 'r' ) )" "$1" 2>&1) || die "JSON Validation error with \"$file\".
+$out"
+}
+
+json_files=$(git diff-index --cached HEAD --diff-filter=AM ) &&
+if test -n "$json_files"; then
+    validate=$(git config --get --bool hooks.ValidateJSON || echo true) &&
+    if test "$validate" = "true"; then
+        python_exe=$(git config hooks.python || type -p python) &&
+        if test -z "$python_exe"; then
+            die 'Cannont validate SimpleITK JSON files with out Python.
+Configure Python's location with:
+
+  git config hooks.python
+        echo "$json_files" |
+        while read src_mode dst_mode src_obj dst_obj status file; do
+            if echo "$file" | egrep-q '\.json$'; then
+                echo "validating $file"
+                validate_json "$file"
+            fi
+        done
+    fi
+fi
