In Python use open over file
The file constructor has been removed in Python 3, open is required.

Change-Id: I623814a2ed3c5b0c3608d4944c19f5c8f32420e2

diff --git a/Utilities/Hooks/pre-commit b/Utilities/Hooks/pre-commit
--- a/Utilities/Hooks/pre-commit
+++ b/Utilities/Hooks/pre-commit
@@ -76,7 +76,7 @@ validate_json() {
     if test -n "$changes"; then
         die "Cannot validate '$1' with work tree changes."
     fi &&
-    out=$($python_exe -c "import sys, json; json.load( file( sys.argv[1], 'r' ) )" "$1" 2>&1) || die "JSON Validation error with \"$file\".
+    out=$($python_exe -c "import sys, json; json.load( open( sys.argv[1], 'r' ) )" "$1" 2>&1) || die "JSON Validation error with \"$file\".
 $out"
 }
 
